version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12
    commands:
      - python3 -m pip install --user pipenv
      - pipenv install --dev
      - pipenv install '-e .'
  pre_build:
    commands:
      - pipenv run pytest
  build:
    commands:
      - pipenv run python setup.py bdist_wheel
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
