version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12
    commands:
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements-dev.txt
      - pip install -r requirements.txt
      - pip install -e .
  pre_build:
    commands:
      - . .venv/bin/activate
      - pytest
  build:
    commands:
      - . .venv/bin/activate
      - python setup.py bdist_wheel
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
