version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12
    commands:
      - yum install -y jq
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements-dev.txt
      - pip install -r requirements.txt
      - pip install -e .
  pre_build:
    commands:
      - . .venv/bin/activate
      - pytest
  build:
    commands:
      - TWINE_USERNAME="__token__"
      - TWINE_PASSWORD=$(aws secretsmanager get-secret-value --secret-id emr-launch-pypi-api-key --query 'SecretString' --output text | jq -r '.["api-key"]')
      - echo $TWINE_USERNAME
      - echo $TWINE_PASSWORD
      - . .venv/bin/activate
      - python setup.py bdist_wheel
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
