version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12
    commands:
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements.txt
      - pip install -r requirements-lambda-layer.txt --target=aws_emr_launch/lambda_sources/layers/emr_config_utils/python/lib/python3.7/site-packages/
      - pip install -e .
  pre_build:
    commands:
      - . .venv/bin/activate
      - pytest
  build:
    commands:
      - . .venv/bin/activate
      - cd ${PROJECT_DIR}
      - $(npm bin)/cdk --verbose --require-approval never deploy -a ./${STACK_FILE} "*"
artifacts:
  files:
    - dist/**/*
  discard-paths: yes
